Add lzo-devel as a Pre-req
lzo-devel is also required to build userspace

Else you get errors like:
vtltape.c:2859: error: ‘LZO_E_OK’ undeclared (first use in this function)
make[1]: *** [vtltape.o] Error 1